In [55]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

Mounted at /content/gdrive


In [56]:
import os
os.chdir('/content/gdrive/MyDrive/CSE564')

In [57]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math

In [58]:
depart_data = pd.read_csv('./depart_2021_3hour.csv')
depart_data.sample(5)

Carrier_Code  Origin_Airport  Destination_Airport  Flight_Season  \
383348              8           205.0                222.0              2   
2041557             9           197.0                120.0              2   
1454232             8           215.0                199.0              2   
1472086             7           192.0                199.0              2   
1917124            10           223.0                174.0              2   

         Flight_Month  Flight_Week  Flight_Day  Scheduled_Departure_Time  \
383348              5           19          13                         9   
2041557             5           20          17                        19   
1454232             3           12          25                         7   
1472086             3           12          26                        17   
1917124             4           14          11                        16   

         Actual_Departure_Time  Departure_Delay  ...  Dep_Wind_Deg_3  \
383348                       9              1.0  ...            30.0   
2041557                     20             22.0  ...            18.0   
1454232                      6             -3.0  ...            26.0   
1472086                     17            -11.0  ...            13.0   
1917124                     16             -5.0  ...            27.0   

         Dep_Clouds_3  Dep_Rain_3  Arr_Temp_3  Arr_Pressure_3  Arr_Humidity_3  \
383348            0.0         0.0        -2.0            11.0             7.0   
2041557           7.0         0.0         1.0             1.0             7.0   
1454232           7.0         0.0        -2.0             1.0             8.0   
1472086           9.0         0.0        -1.0             4.0             7.0   
1917124           2.0         0.0         0.0           -14.0             5.0   

         Arr_Wind_Speed_3  Arr_Wind_Deg_3  Arr_Clouds_3  Arr_Rain_3  
383348                  3            19.0           2.0         0.0  
2041557                 7            16.0           9.0         1.0  
1454232                 9            33.0           9.0         0.0  
1472086                 2             2.0           0.0         0.0  
1917124                 5            22.0           7.0         0.0  

[5 rows x 26 columns]

In [59]:
depart_data.columns

Index(['Carrier_Code', 'Origin_Airport', 'Destination_Airport',
       'Flight_Season', 'Flight_Month', 'Flight_Week', 'Flight_Day',
       'Scheduled_Departure_Time', 'Actual_Departure_Time', 'Departure_Delay',
       'Arrival_Delay', 'Delayed', 'Dep_Temp_3', 'Dep_Pressure_3',
       'Dep_Humidity_3', 'Dep_Wind_Speed_3', 'Dep_Wind_Deg_3', 'Dep_Clouds_3',
       'Dep_Rain_3', 'Arr_Temp_3', 'Arr_Pressure_3', 'Arr_Humidity_3',
       'Arr_Wind_Speed_3', 'Arr_Wind_Deg_3', 'Arr_Clouds_3', 'Arr_Rain_3'],
      dtype='object')

In [60]:
only_delayed_data = depart_data[depart_data.Delayed == 1]
only_delayed_data.sample(5)

Carrier_Code  Origin_Airport  Destination_Airport  Flight_Season  \
1764798             8           217.0                202.0              3   
1630222             2           223.0                194.0              3   
460030              2           214.0                219.0              3   
1179061             7           201.0                216.0              3   
2237664             5           207.0                 83.0              3   

         Flight_Month  Flight_Week  Flight_Day  Scheduled_Departure_Time  \
1764798             7           29          19                        19   
1630222             8           31           3                        14   
460030              7           29          19                        20   
1179061             6           26          28                        17   
2237664             7           29          23                        18   

         Actual_Departure_Time  Departure_Delay  ...  Dep_Wind_Deg_3  \
1764798                     19             16.0  ...            23.0   
1630222                     15             61.0  ...             8.0   
460030                      21             10.0  ...             0.0   
1179061                     18             44.0  ...            21.0   
2237664                     18             24.0  ...             3.0   

         Dep_Clouds_3  Dep_Rain_3  Arr_Temp_3  Arr_Pressure_3  Arr_Humidity_3  \
1764798           2.0         0.0         2.0             4.0             7.0   
1630222           7.0         0.0         1.0             7.0             6.0   
460030            7.0         0.0         3.0             2.0             3.0   
1179061           7.0         0.0         4.0            -6.0             3.0   
2237664           2.0         0.0         2.0             6.0             5.0   

         Arr_Wind_Speed_3  Arr_Wind_Deg_3  Arr_Clouds_3  Arr_Rain_3  
1764798                10             7.0           2.0         0.0  
1630222                 0             2.0           9.0         0.0  
460030                  2             9.0           0.0         0.0  
1179061                 6             1.0           0.0         0.0  
2237664                 5             2.0           4.0         0.0  

[5 rows x 26 columns]

In [61]:
len(only_delayed_data)

756313

In [62]:
only_delayed_data = only_delayed_data.drop(['Arrival_Delay', 'Delayed','Arr_Temp_3', 'Arr_Pressure_3', 'Arr_Humidity_3',
       'Arr_Wind_Speed_3', 'Arr_Wind_Deg_3', 'Arr_Clouds_3', 'Arr_Rain_3'], axis=1)

In [63]:
unique, count = np.unique(only_delayed_data.Carrier_Code, return_counts=True)

In [64]:
weight = count
sum = count.sum()
for i in range(len(unique)):
  weight[i] = int(float(count[i])/ float(sum) * 500.0 + 1)
weight 

array([ 24,  15,  36,   8,  26,  91,  28,  57, 146,  74])

In [65]:
unique

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
only_delayed_data.drop(only_delayed_data[only_delayed_data['Carrier_Code'] == 1].index, inplace = True)
only_delayed_data.drop(only_delayed_data[only_delayed_data['Carrier_Code'] == 2].index, inplace = True)
only_delayed_data.drop(only_delayed_data[only_delayed_data['Carrier_Code'] == 4].index, inplace = True)
only_delayed_data.drop(only_delayed_data[only_delayed_data['Carrier_Code'] == 5].index, inplace = True)
only_delayed_data.drop(only_delayed_data[only_delayed_data['Carrier_Code'] == 7].index, inplace = True)

In [67]:
unique, count = np.unique(only_delayed_data.Carrier_Code, return_counts=True)
weight = count
sum = count.sum()
for i in range(len(unique)):
  weight[i] = int(float(count[i])/ float(sum) * 500.0 + 1)
weight 

array([ 44, 113,  71, 182,  92])

In [68]:
unique

array([ 3,  6,  8,  9, 10])

In [69]:
stratified_data = pd.DataFrame(columns=['Carrier_Code', 'Origin_Airport', 'Destination_Airport',
       'Flight_Season', 'Flight_Month', 'Flight_Week', 'Flight_Day',
       'Scheduled_Departure_Time', 'Actual_Departure_Time', 'Departure_Delay', 'Dep_Temp_3', 'Dep_Pressure_3',
       'Dep_Humidity_3', 'Dep_Wind_Speed_3', 'Dep_Wind_Deg_3', 'Dep_Clouds_3',
       'Dep_Rain_3'])
for i in range(len(weight)):
  current = only_delayed_data[only_delayed_data.Carrier_Code ==unique[i]]
  current = current.sample(n=weight[i],random_state=1)
  stratified_data = pd.concat([stratified_data, current], ignore_index=True)

stratified_data.sample(5)

Carrier_Code  Origin_Airport  Destination_Airport Flight_Season  \
22             3           213.0                102.0             3   
37             3           208.0                206.0             3   
70             6           221.0                179.0             2   
311            9           213.0                208.0             3   
495           10           223.0                221.0             2   

    Flight_Month Flight_Week Flight_Day Scheduled_Departure_Time  \
22             7          30         27                       16   
37             6          26         30                       15   
70             5          18          7                       10   
311            6          25         25                       15   
495            4          14          9                       18   

    Actual_Departure_Time  Departure_Delay  Dep_Temp_3  Dep_Pressure_3  \
22                     17             35.0         2.0             3.0   
37                     17            119.0         2.0             6.0   
70                     10             -5.0         0.0             8.0   
311                    15             -1.0         2.0             4.0   
495                    19             10.0         1.0             2.0   

     Dep_Humidity_3 Dep_Wind_Speed_3  Dep_Wind_Deg_3  Dep_Clouds_3  Dep_Rain_3  
22              7.0                0             0.0           2.0         0.0  
37              6.0                2            22.0           2.0         0.0  
70              6.0                3             7.0           0.0         0.0  
311             8.0                8            11.0           7.0         0.0  
495             7.0                3            19.0           7.0         0.0

In [70]:
len(stratified_data)

502

In [71]:
stratified_data = stratified_data.drop(["Destination_Airport"], axis=1)

In [72]:
stratified_data.dtypes

Carrier_Code                 object
Origin_Airport              float64
Flight_Season                object
Flight_Month                 object
Flight_Week                  object
Flight_Day                   object
Scheduled_Departure_Time     object
Actual_Departure_Time        object
Departure_Delay             float64
Dep_Temp_3                  float64
Dep_Pressure_3              float64
Dep_Humidity_3              float64
Dep_Wind_Speed_3             object
Dep_Wind_Deg_3              float64
Dep_Clouds_3                float64
Dep_Rain_3                  float64
dtype: object

In [73]:
stratified_data.columns

Index(['Carrier_Code', 'Origin_Airport', 'Flight_Season', 'Flight_Month',
       'Flight_Week', 'Flight_Day', 'Scheduled_Departure_Time',
       'Actual_Departure_Time', 'Departure_Delay', 'Dep_Temp_3',
       'Dep_Pressure_3', 'Dep_Humidity_3', 'Dep_Wind_Speed_3',
       'Dep_Wind_Deg_3', 'Dep_Clouds_3', 'Dep_Rain_3'],
      dtype='object')

In [74]:
depart_data = pd.read_csv('./depart_combined_2021.csv')
depart_data.sample(5)

Carrier_Code        Date  Flight_Number Tail_Number  \
855283            DL  04/30/2021         2426.0      N542US   
757636            NK  04/18/2021          937.0      N627NK   
2301323           G4  03/30/2021          934.0       259NV   
739978            AA  04/14/2021         2600.0      N950NN   
2110510           DL  08/22/2021         1382.0      N827DN   

        Destination_Airport Scheduled_Departure_Time Actual_Departure_Time  \
855283                  SLC                    14:05                 14:02   
757636                  ATL                    13:00                 12:50   
2301323                 ROA                    15:20                 15:12   
739978                  DFW                    08:00                 07:55   
2110510                 SEA                    01:05                 01:03   

         Scheduled_Elapsed_Time  Actual_Elapsed_Time  Departure_Delay  ...  \
855283                    110.0                103.0             -3.0  ...   
757636                    128.0                129.0            -10.0  ...   
2301323                   114.0                112.0             -8.0  ...   
739978                    270.0                290.0             -5.0  ...   
2110510                   198.0                171.0             -2.0  ...   

        Dep_Wind_Deg_3  Dep_Clouds_3  Dep_Rain_3  Arr_Temp_3  Arr_Pressure_3  \
855283            80.0           1.0         0.0      283.95          1026.0   
757636           260.0          90.0         0.0      283.94          1014.0   
2301323           90.0          90.0         0.0      284.58          1028.0   
739978           130.0          75.0         0.0      291.36          1015.0   
2110510          121.0          89.0         0.0      291.97          1010.0   

         Arr_Humidity_3  Arr_Wind_Speed_3 Arr_Wind_Deg_3  Arr_Clouds_3  \
855283             58.0              3.60          130.0          75.0   
757636             66.0              3.09          320.0          75.0   
2301323            50.0              1.54          150.0           1.0   
739978             55.0              7.72          360.0          75.0   
2110510            64.0              3.60          210.0          90.0   

         Arr_Rain_3  
855283          0.0  
757636          0.0  
2301323         0.0  
739978          0.0  
2110510         0.0  

[5 rows x 82 columns]

In [75]:
depart_data = depart_data[depart_data['Actual_Elapsed_Time'] != 0]

In [76]:
# airport integerize
airports_code = pd.read_csv('./airports.csv')
depart_destination_counts = depart_data['Destination_Airport'].value_counts().reset_index()
depart_destination_counts.columns = ['Airport', 'Code']
num = depart_destination_counts.shape[0]
depart_destination_counts['Code'] = [num+1]*num - depart_destination_counts.index
airports_code = pd.merge(airports_code, depart_destination_counts, how='outer')
airports_code.drop(['Code (int)'], axis=1, inplace=True)
airports_code.fillna(0, inplace=True)
airports_code

Airport   Code
0       ABR    0.0
1       ABI    0.0
2       ADK   12.0
3       BQN  104.0
4       CAK   53.0
..      ...    ...
428     YKM    0.0
429     YAK   81.0
430     YAP    0.0
431     YNG    0.0
432     YUM    0.0

[433 rows x 2 columns]

In [44]:
airports_code.to_csv("airports_code_with_value.csv", index=False)

In [ ]:
air_dict = airports_code.set_index('Code').T.to_dict('list')
airport_abbr = []
#airport_loc = []
for index, row in stratified_data.iterrows():
    # print(row)
    # break
    airport_abbr.append(air_dict[row["Origin_Airport"]][0])
airport_abbr

In [83]:
stratified_data["Airport_Abbr"] = airport_abbr

In [85]:
geo_data = pd.read_csv("./airports_geographic_coordinates.csv")
geo_data.sample(5)

Airport  Lat(N)  Lng(W)  GMT
364     CRW   38.37   81.59   -5
334     DFW   32.89   97.04   -6
196     MMH   37.62  118.84   -8
133     OXR   34.19  119.20   -8
120     PUB   38.28  104.49   -7

In [86]:
geo_dict = geo_data.set_index('Airport').T.to_dict("list")
Lat_N = []
Lng_W = []
GMT = []
for index,row in stratified_data.iterrows():
    Lat_N.append(geo_dict[row["Airport_Abbr"]][0])
    Lng_W.append(geo_dict[row["Airport_Abbr"]][1])
    GMT.append(geo_dict[row["Airport_Abbr"]][2])

stratified_data["Lat_N"] = Lat_N
stratified_data["Lng_W"] = Lng_W
stratified_data["GMT"] = GMT

stratified_data.iloc[0]

Carrier_Code                     3
Origin_Airport               186.0
Flight_Season                    1
Flight_Month                     2
Flight_Week                      5
Flight_Day                       1
Scheduled_Departure_Time         9
Actual_Departure_Time            9
Departure_Delay               -1.0
Dep_Temp_3                    -1.0
Dep_Pressure_3                 6.0
Dep_Humidity_3                 5.0
Dep_Wind_Speed_3                 1
Dep_Wind_Deg_3                28.0
Dep_Clouds_3                   9.0
Dep_Rain_3                     0.0
Airport_Abbr                   SNA
Lat_N                        33.67
Lng_W                       117.86
GMT                           -8.0
Name: 0, dtype: object

In [ ]:
airlines_dict = {1:'G4' , 2:'F9', 3: 'NK', 4:'HA', 5:'B6', 6:'AA' ,7:'AS', 8:'UA', 9:'WN', 10:'DL'}

airline_abbr = []
for index, row in stratified_data.iterrows():
    airline_abbr.append(airlines_dict[row["Carrier_Code"]])
airline_abbr

In [90]:
stratified_data["Carrier_Abbr"] = airline_abbr

In [91]:
stratified_data.iloc[0]

Carrier_Code                     3
Origin_Airport               186.0
Flight_Season                    1
Flight_Month                     2
Flight_Week                      5
Flight_Day                       1
Scheduled_Departure_Time         9
Actual_Departure_Time            9
Departure_Delay               -1.0
Dep_Temp_3                    -1.0
Dep_Pressure_3                 6.0
Dep_Humidity_3                 5.0
Dep_Wind_Speed_3                 1
Dep_Wind_Deg_3                28.0
Dep_Clouds_3                   9.0
Dep_Rain_3                     0.0
Airport_Abbr                   SNA
Lat_N                        33.67
Lng_W                       117.86
GMT                           -8.0
Carrier_Abbr                    NK
Name: 0, dtype: object

In [92]:
stratified_data.to_csv("stratified_data.csv")